tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
      gp ports await 8000
      gp preview $(gp url 8000)
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
