tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 8000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
